version: '3'
services:
  backend:
    build: .
    # depends_on:
    #   - redis
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    networks:
      - imonir
    # network_mode: "bridge"
    volumes:
     - .:/home/app
     - node_modules:/home/app/node_modules
  # redis:
  #   image: redis:3.2-alpine
  #   expose:
  #     - 6379
  #   volumes: 
  #     - redis_data:/data
volumes: 
  node_modules:
  # redis_data:

networks:
  imonir:
    external: true
